FROM nginx:1.27-alpine

# Copy custom nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Create nginx logs directory
RUN mkdir -p /var/log/nginx

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]
