port 26379
daemonize no
pidfile /var/run/redis-sentinel-1.pid
logfile ""
dir /tmp

sentinel monitor mymaster redis-master 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel parallel-syncs mymaster 1
sentinel failover-timeout mymaster 10000

sentinel deny-scripts-reconfig yes
